### ISSUE TITLE
Add a default IconSet

### ISSUE THREAD

**Issue by marinelligiovanna** [ponciusz/icomoon-react#25]
Hi Ponciusz, how are you?

First of all, I would like to say that you made a great job creating this library! I have my own Icomoon component in some of my projects but yours seems more complete and carefully done. I would love to use it on my projects.

One thing that bothers me a little bit is the fact that you must to create a wrapper for the Icomoon component even that you want to use the default IconSet. It would be great to include the default IconSet (selection.json) as a default prop. Of course that if you want another icon set, you can not run from creating a wrapper.

Please check my pull request to see if you agree that a default IconSet is suitable for the Icomoon component.

**Comment by marinelligiovanna** [comment]
By the way, do you have any intend to add other icon sets? It would be great to have other icons such as from Material Design.  Let me know if you want help with it.

Best Regards!

**Comment by ponciusz** [comment]
Hi, Thanks for the comment.  The idea of icomoon-react is that it is minimal as possible. So the only thing I push to [NPM](https://www.npmjs.com/package/icomoon-react) is `IcomoonReact` component there are a lot of ready repositories with material icons etc the purpose of this component is a fully flexible and customizable set of icons. Unfortunately, I can't accept PR because I will be pushed to NPM and increase the weight of component and most of the time users will not use default iconset at all.

All material icons can be added easily when the user is creating custom [iconset](https://icomoon.io/app/#/select/library) (the thing is that I'm against it because we should add only things we use)
